name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          echo "Deployment started"
          sudo ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.AWS_SERVER_IP }} << 'EOF'
            cd /var/www/html/secret-manager
            sudo chmod -R 777 ./storage
            sudo chmod -R 777 ./bootstrap
            sudo git pull origin main
            sudo composer update
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo systemctl restart nginx
            echo "Deployed Successfully"

          EOF
