name: Deploy Laravel to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          echo "Deployment started"
          ssh -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.AWS_SERVER_IP }} << 'EOF'
            echo "Starting deployment on EC2..."

            cd /var/www/html/secret-manager
            sudo git config --global --add safe.directory /var/www/html/secret-manager

            sudo chmod -R 775 storage bootstrap/cache
            sudo chown -R www-data:www-data storage bootstrap/cache

            sudo git pull origin main

            sudo php artisan config:clear
            sudo php artisan config:cache
            sudo php artisan route:clear
            sudo php artisan route:cache

            # Restart the web server
            sudo systemctl restart nginx

            echo "Deployed Successfully"
          EOF
